/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AAndInfixBinInfixOp extends PBinInfixOp
{
    private TBopAnd _bopAnd_;

    public AAndInfixBinInfixOp()
    {
        // Constructor
    }

    public AAndInfixBinInfixOp(
        @SuppressWarnings("hiding") TBopAnd _bopAnd_)
    {
        // Constructor
        setBopAnd(_bopAnd_);

    }

    @Override
    public Object clone()
    {
        return new AAndInfixBinInfixOp(
            cloneNode(this._bopAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndInfixBinInfixOp(this);
    }

    public TBopAnd getBopAnd()
    {
        return this._bopAnd_;
    }

    public void setBopAnd(TBopAnd node)
    {
        if(this._bopAnd_ != null)
        {
            this._bopAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bopAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bopAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bopAnd_ == child)
        {
            this._bopAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bopAnd_ == oldChild)
        {
            setBopAnd((TBopAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
