/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AArrayOperationAddArrayOp extends PArrayOp
{
    private PArrayAdd _arrayAdd_;

    public AArrayOperationAddArrayOp()
    {
        // Constructor
    }

    public AArrayOperationAddArrayOp(
        @SuppressWarnings("hiding") PArrayAdd _arrayAdd_)
    {
        // Constructor
        setArrayAdd(_arrayAdd_);

    }

    @Override
    public Object clone()
    {
        return new AArrayOperationAddArrayOp(
            cloneNode(this._arrayAdd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayOperationAddArrayOp(this);
    }

    public PArrayAdd getArrayAdd()
    {
        return this._arrayAdd_;
    }

    public void setArrayAdd(PArrayAdd node)
    {
        if(this._arrayAdd_ != null)
        {
            this._arrayAdd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayAdd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayAdd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayAdd_ == child)
        {
            this._arrayAdd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayAdd_ == oldChild)
        {
            setArrayAdd((PArrayAdd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
