/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AArrayExprPrimeExtraArrayExprPrime extends PArrayExprPrime
{
    private TSopComma _sopComma_;
    private PVal _val_;
    private PArrayExprPrime _arrayExprPrime_;

    public AArrayExprPrimeExtraArrayExprPrime()
    {
        // Constructor
    }

    public AArrayExprPrimeExtraArrayExprPrime(
        @SuppressWarnings("hiding") TSopComma _sopComma_,
        @SuppressWarnings("hiding") PVal _val_,
        @SuppressWarnings("hiding") PArrayExprPrime _arrayExprPrime_)
    {
        // Constructor
        setSopComma(_sopComma_);

        setVal(_val_);

        setArrayExprPrime(_arrayExprPrime_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExprPrimeExtraArrayExprPrime(
            cloneNode(this._sopComma_),
            cloneNode(this._val_),
            cloneNode(this._arrayExprPrime_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExprPrimeExtraArrayExprPrime(this);
    }

    public TSopComma getSopComma()
    {
        return this._sopComma_;
    }

    public void setSopComma(TSopComma node)
    {
        if(this._sopComma_ != null)
        {
            this._sopComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopComma_ = node;
    }

    public PVal getVal()
    {
        return this._val_;
    }

    public void setVal(PVal node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    public PArrayExprPrime getArrayExprPrime()
    {
        return this._arrayExprPrime_;
    }

    public void setArrayExprPrime(PArrayExprPrime node)
    {
        if(this._arrayExprPrime_ != null)
        {
            this._arrayExprPrime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayExprPrime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopComma_)
            + toString(this._val_)
            + toString(this._arrayExprPrime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopComma_ == child)
        {
            this._sopComma_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        if(this._arrayExprPrime_ == child)
        {
            this._arrayExprPrime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopComma_ == oldChild)
        {
            setSopComma((TSopComma) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PVal) newChild);
            return;
        }

        if(this._arrayExprPrime_ == oldChild)
        {
            setArrayExprPrime((PArrayExprPrime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
