/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACountSpecialSyntax extends PSpecialSyntax
{
    private TSopCount _sopCount_;

    public ACountSpecialSyntax()
    {
        // Constructor
    }

    public ACountSpecialSyntax(
        @SuppressWarnings("hiding") TSopCount _sopCount_)
    {
        // Constructor
        setSopCount(_sopCount_);

    }

    @Override
    public Object clone()
    {
        return new ACountSpecialSyntax(
            cloneNode(this._sopCount_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACountSpecialSyntax(this);
    }

    public TSopCount getSopCount()
    {
        return this._sopCount_;
    }

    public void setSopCount(TSopCount node)
    {
        if(this._sopCount_ != null)
        {
            this._sopCount_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopCount_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopCount_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopCount_ == child)
        {
            this._sopCount_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopCount_ == oldChild)
        {
            setSopCount((TSopCount) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
