/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACsvOperationRemoveAtCsvOp extends PCsvOp
{
    private PCsvRemoveAt _csvRemoveAt_;

    public ACsvOperationRemoveAtCsvOp()
    {
        // Constructor
    }

    public ACsvOperationRemoveAtCsvOp(
        @SuppressWarnings("hiding") PCsvRemoveAt _csvRemoveAt_)
    {
        // Constructor
        setCsvRemoveAt(_csvRemoveAt_);

    }

    @Override
    public Object clone()
    {
        return new ACsvOperationRemoveAtCsvOp(
            cloneNode(this._csvRemoveAt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACsvOperationRemoveAtCsvOp(this);
    }

    public PCsvRemoveAt getCsvRemoveAt()
    {
        return this._csvRemoveAt_;
    }

    public void setCsvRemoveAt(PCsvRemoveAt node)
    {
        if(this._csvRemoveAt_ != null)
        {
            this._csvRemoveAt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._csvRemoveAt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._csvRemoveAt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._csvRemoveAt_ == child)
        {
            this._csvRemoveAt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._csvRemoveAt_ == oldChild)
        {
            setCsvRemoveAt((PCsvRemoveAt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
