/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ACsvOrientationRowOrientation extends POrientation
{
    private TKwRow _kwRow_;

    public ACsvOrientationRowOrientation()
    {
        // Constructor
    }

    public ACsvOrientationRowOrientation(
        @SuppressWarnings("hiding") TKwRow _kwRow_)
    {
        // Constructor
        setKwRow(_kwRow_);

    }

    @Override
    public Object clone()
    {
        return new ACsvOrientationRowOrientation(
            cloneNode(this._kwRow_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACsvOrientationRowOrientation(this);
    }

    public TKwRow getKwRow()
    {
        return this._kwRow_;
    }

    public void setKwRow(TKwRow node)
    {
        if(this._kwRow_ != null)
        {
            this._kwRow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwRow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwRow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwRow_ == child)
        {
            this._kwRow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwRow_ == oldChild)
        {
            setKwRow((TKwRow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
