/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADivisionInfixBinInfixOp extends PBinInfixOp
{
    private TOpDiv _opDiv_;

    public ADivisionInfixBinInfixOp()
    {
        // Constructor
    }

    public ADivisionInfixBinInfixOp(
        @SuppressWarnings("hiding") TOpDiv _opDiv_)
    {
        // Constructor
        setOpDiv(_opDiv_);

    }

    @Override
    public Object clone()
    {
        return new ADivisionInfixBinInfixOp(
            cloneNode(this._opDiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisionInfixBinInfixOp(this);
    }

    public TOpDiv getOpDiv()
    {
        return this._opDiv_;
    }

    public void setOpDiv(TOpDiv node)
    {
        if(this._opDiv_ != null)
        {
            this._opDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opDiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opDiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opDiv_ == child)
        {
            this._opDiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opDiv_ == oldChild)
        {
            setOpDiv((TOpDiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
