/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AEqualityInfixBinInfixOp extends PBinInfixOp
{
    private TBopEq _bopEq_;

    public AEqualityInfixBinInfixOp()
    {
        // Constructor
    }

    public AEqualityInfixBinInfixOp(
        @SuppressWarnings("hiding") TBopEq _bopEq_)
    {
        // Constructor
        setBopEq(_bopEq_);

    }

    @Override
    public Object clone()
    {
        return new AEqualityInfixBinInfixOp(
            cloneNode(this._bopEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualityInfixBinInfixOp(this);
    }

    public TBopEq getBopEq()
    {
        return this._bopEq_;
    }

    public void setBopEq(TBopEq node)
    {
        if(this._bopEq_ != null)
        {
            this._bopEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bopEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bopEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bopEq_ == child)
        {
            this._bopEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bopEq_ == oldChild)
        {
            setBopEq((TBopEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
