/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AExprArrayExpr extends PExpr
{
    private PArrayExpr _arrayExpr_;

    public AExprArrayExpr()
    {
        // Constructor
    }

    public AExprArrayExpr(
        @SuppressWarnings("hiding") PArrayExpr _arrayExpr_)
    {
        // Constructor
        setArrayExpr(_arrayExpr_);

    }

    @Override
    public Object clone()
    {
        return new AExprArrayExpr(
            cloneNode(this._arrayExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprArrayExpr(this);
    }

    public PArrayExpr getArrayExpr()
    {
        return this._arrayExpr_;
    }

    public void setArrayExpr(PArrayExpr node)
    {
        if(this._arrayExpr_ != null)
        {
            this._arrayExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayExpr_ == child)
        {
            this._arrayExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayExpr_ == oldChild)
        {
            setArrayExpr((PArrayExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
