/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AExprPrimeOperatorValPrimeExprPrime extends PExprPrime
{
    private PBinInfixOp _binInfixOp_;
    private PVal _val_;
    private PExprPrime _exprPrime_;

    public AExprPrimeOperatorValPrimeExprPrime()
    {
        // Constructor
    }

    public AExprPrimeOperatorValPrimeExprPrime(
        @SuppressWarnings("hiding") PBinInfixOp _binInfixOp_,
        @SuppressWarnings("hiding") PVal _val_,
        @SuppressWarnings("hiding") PExprPrime _exprPrime_)
    {
        // Constructor
        setBinInfixOp(_binInfixOp_);

        setVal(_val_);

        setExprPrime(_exprPrime_);

    }

    @Override
    public Object clone()
    {
        return new AExprPrimeOperatorValPrimeExprPrime(
            cloneNode(this._binInfixOp_),
            cloneNode(this._val_),
            cloneNode(this._exprPrime_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprPrimeOperatorValPrimeExprPrime(this);
    }

    public PBinInfixOp getBinInfixOp()
    {
        return this._binInfixOp_;
    }

    public void setBinInfixOp(PBinInfixOp node)
    {
        if(this._binInfixOp_ != null)
        {
            this._binInfixOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._binInfixOp_ = node;
    }

    public PVal getVal()
    {
        return this._val_;
    }

    public void setVal(PVal node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    public PExprPrime getExprPrime()
    {
        return this._exprPrime_;
    }

    public void setExprPrime(PExprPrime node)
    {
        if(this._exprPrime_ != null)
        {
            this._exprPrime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprPrime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._binInfixOp_)
            + toString(this._val_)
            + toString(this._exprPrime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._binInfixOp_ == child)
        {
            this._binInfixOp_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        if(this._exprPrime_ == child)
        {
            this._exprPrime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._binInfixOp_ == oldChild)
        {
            setBinInfixOp((PBinInfixOp) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PVal) newChild);
            return;
        }

        if(this._exprPrime_ == oldChild)
        {
            setExprPrime((PExprPrime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
