/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AFilterSpecialSyntax extends PSpecialSyntax
{
    private TSopFilter _sopFilter_;
    private TId _id_;

    public AFilterSpecialSyntax()
    {
        // Constructor
    }

    public AFilterSpecialSyntax(
        @SuppressWarnings("hiding") TSopFilter _sopFilter_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setSopFilter(_sopFilter_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AFilterSpecialSyntax(
            cloneNode(this._sopFilter_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilterSpecialSyntax(this);
    }

    public TSopFilter getSopFilter()
    {
        return this._sopFilter_;
    }

    public void setSopFilter(TSopFilter node)
    {
        if(this._sopFilter_ != null)
        {
            this._sopFilter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopFilter_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopFilter_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopFilter_ == child)
        {
            this._sopFilter_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopFilter_ == oldChild)
        {
            setSopFilter((TSopFilter) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
