/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AFilterexprFilterexpr extends PFilterexpr
{
    private TSopComma _sopComma_;
    private PExpr _expr_;

    public AFilterexprFilterexpr()
    {
        // Constructor
    }

    public AFilterexprFilterexpr(
        @SuppressWarnings("hiding") TSopComma _sopComma_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setSopComma(_sopComma_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AFilterexprFilterexpr(
            cloneNode(this._sopComma_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilterexprFilterexpr(this);
    }

    public TSopComma getSopComma()
    {
        return this._sopComma_;
    }

    public void setSopComma(TSopComma node)
    {
        if(this._sopComma_ != null)
        {
            this._sopComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopComma_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopComma_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopComma_ == child)
        {
            this._sopComma_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopComma_ == oldChild)
        {
            setSopComma((TSopComma) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
