/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AFilterPrefixFilter extends PFilter
{
    private TSopFilter _sopFilter_;
    private PExpr _expr_;

    public AFilterPrefixFilter()
    {
        // Constructor
    }

    public AFilterPrefixFilter(
        @SuppressWarnings("hiding") TSopFilter _sopFilter_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setSopFilter(_sopFilter_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AFilterPrefixFilter(
            cloneNode(this._sopFilter_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilterPrefixFilter(this);
    }

    public TSopFilter getSopFilter()
    {
        return this._sopFilter_;
    }

    public void setSopFilter(TSopFilter node)
    {
        if(this._sopFilter_ != null)
        {
            this._sopFilter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopFilter_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopFilter_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopFilter_ == child)
        {
            this._sopFilter_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopFilter_ == oldChild)
        {
            setSopFilter((TSopFilter) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
