/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AGroupbySpecialSyntax extends PSpecialSyntax
{
    private TSopGroupby _sopGroupby_;
    private TId _id_;

    public AGroupbySpecialSyntax()
    {
        // Constructor
    }

    public AGroupbySpecialSyntax(
        @SuppressWarnings("hiding") TSopGroupby _sopGroupby_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setSopGroupby(_sopGroupby_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AGroupbySpecialSyntax(
            cloneNode(this._sopGroupby_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupbySpecialSyntax(this);
    }

    public TSopGroupby getSopGroupby()
    {
        return this._sopGroupby_;
    }

    public void setSopGroupby(TSopGroupby node)
    {
        if(this._sopGroupby_ != null)
        {
            this._sopGroupby_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopGroupby_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopGroupby_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopGroupby_ == child)
        {
            this._sopGroupby_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopGroupby_ == oldChild)
        {
            setSopGroupby((TSopGroupby) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
