/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AGroupbyOpSpecialSyntax extends PSpecialSyntax
{
    private TSopGroupby _sopGroupby_;

    public AGroupbyOpSpecialSyntax()
    {
        // Constructor
    }

    public AGroupbyOpSpecialSyntax(
        @SuppressWarnings("hiding") TSopGroupby _sopGroupby_)
    {
        // Constructor
        setSopGroupby(_sopGroupby_);

    }

    @Override
    public Object clone()
    {
        return new AGroupbyOpSpecialSyntax(
            cloneNode(this._sopGroupby_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupbyOpSpecialSyntax(this);
    }

    public TSopGroupby getSopGroupby()
    {
        return this._sopGroupby_;
    }

    public void setSopGroupby(TSopGroupby node)
    {
        if(this._sopGroupby_ != null)
        {
            this._sopGroupby_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopGroupby_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopGroupby_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopGroupby_ == child)
        {
            this._sopGroupby_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopGroupby_ == oldChild)
        {
            setSopGroupby((TSopGroupby) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
