/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AImportStmtStmt extends PStmt
{
    private PImportT _importT_;

    public AImportStmtStmt()
    {
        // Constructor
    }

    public AImportStmtStmt(
        @SuppressWarnings("hiding") PImportT _importT_)
    {
        // Constructor
        setImportT(_importT_);

    }

    @Override
    public Object clone()
    {
        return new AImportStmtStmt(
            cloneNode(this._importT_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImportStmtStmt(this);
    }

    public PImportT getImportT()
    {
        return this._importT_;
    }

    public void setImportT(PImportT node)
    {
        if(this._importT_ != null)
        {
            this._importT_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._importT_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._importT_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._importT_ == child)
        {
            this._importT_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._importT_ == oldChild)
        {
            setImportT((PImportT) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
