/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ALessThanInfixBinInfixOp extends PBinInfixOp
{
    private TBopLthan _bopLthan_;

    public ALessThanInfixBinInfixOp()
    {
        // Constructor
    }

    public ALessThanInfixBinInfixOp(
        @SuppressWarnings("hiding") TBopLthan _bopLthan_)
    {
        // Constructor
        setBopLthan(_bopLthan_);

    }

    @Override
    public Object clone()
    {
        return new ALessThanInfixBinInfixOp(
            cloneNode(this._bopLthan_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessThanInfixBinInfixOp(this);
    }

    public TBopLthan getBopLthan()
    {
        return this._bopLthan_;
    }

    public void setBopLthan(TBopLthan node)
    {
        if(this._bopLthan_ != null)
        {
            this._bopLthan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bopLthan_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bopLthan_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bopLthan_ == child)
        {
            this._bopLthan_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bopLthan_ == oldChild)
        {
            setBopLthan((TBopLthan) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
