/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AMeanSpecialSyntax extends PSpecialSyntax
{
    private TSopMean _sopMean_;
    private PExpr _expr_;

    public AMeanSpecialSyntax()
    {
        // Constructor
    }

    public AMeanSpecialSyntax(
        @SuppressWarnings("hiding") TSopMean _sopMean_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setSopMean(_sopMean_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AMeanSpecialSyntax(
            cloneNode(this._sopMean_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMeanSpecialSyntax(this);
    }

    public TSopMean getSopMean()
    {
        return this._sopMean_;
    }

    public void setSopMean(TSopMean node)
    {
        if(this._sopMean_ != null)
        {
            this._sopMean_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopMean_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopMean_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopMean_ == child)
        {
            this._sopMean_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopMean_ == oldChild)
        {
            setSopMean((TSopMean) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
