/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ARemoveFromCsvCsvOp extends PCsvOp
{
    private TKwRemoveLast _kwRemoveLast_;
    private POrientation _orientation_;
    private TKwIn _kwIn_;
    private TId _id_;

    public ARemoveFromCsvCsvOp()
    {
        // Constructor
    }

    public ARemoveFromCsvCsvOp(
        @SuppressWarnings("hiding") TKwRemoveLast _kwRemoveLast_,
        @SuppressWarnings("hiding") POrientation _orientation_,
        @SuppressWarnings("hiding") TKwIn _kwIn_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setKwRemoveLast(_kwRemoveLast_);

        setOrientation(_orientation_);

        setKwIn(_kwIn_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new ARemoveFromCsvCsvOp(
            cloneNode(this._kwRemoveLast_),
            cloneNode(this._orientation_),
            cloneNode(this._kwIn_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARemoveFromCsvCsvOp(this);
    }

    public TKwRemoveLast getKwRemoveLast()
    {
        return this._kwRemoveLast_;
    }

    public void setKwRemoveLast(TKwRemoveLast node)
    {
        if(this._kwRemoveLast_ != null)
        {
            this._kwRemoveLast_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwRemoveLast_ = node;
    }

    public POrientation getOrientation()
    {
        return this._orientation_;
    }

    public void setOrientation(POrientation node)
    {
        if(this._orientation_ != null)
        {
            this._orientation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orientation_ = node;
    }

    public TKwIn getKwIn()
    {
        return this._kwIn_;
    }

    public void setKwIn(TKwIn node)
    {
        if(this._kwIn_ != null)
        {
            this._kwIn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwIn_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwRemoveLast_)
            + toString(this._orientation_)
            + toString(this._kwIn_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwRemoveLast_ == child)
        {
            this._kwRemoveLast_ = null;
            return;
        }

        if(this._orientation_ == child)
        {
            this._orientation_ = null;
            return;
        }

        if(this._kwIn_ == child)
        {
            this._kwIn_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwRemoveLast_ == oldChild)
        {
            setKwRemoveLast((TKwRemoveLast) newChild);
            return;
        }

        if(this._orientation_ == oldChild)
        {
            setOrientation((POrientation) newChild);
            return;
        }

        if(this._kwIn_ == oldChild)
        {
            setKwIn((TKwIn) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
