/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ASpecialExprPrimeSpecialExprPrime extends PSpecialExprPrime
{
    private PSpecialOp _specialOp_;
    private PSpecialExprPrime _specialExprPrime_;

    public ASpecialExprPrimeSpecialExprPrime()
    {
        // Constructor
    }

    public ASpecialExprPrimeSpecialExprPrime(
        @SuppressWarnings("hiding") PSpecialOp _specialOp_,
        @SuppressWarnings("hiding") PSpecialExprPrime _specialExprPrime_)
    {
        // Constructor
        setSpecialOp(_specialOp_);

        setSpecialExprPrime(_specialExprPrime_);

    }

    @Override
    public Object clone()
    {
        return new ASpecialExprPrimeSpecialExprPrime(
            cloneNode(this._specialOp_),
            cloneNode(this._specialExprPrime_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpecialExprPrimeSpecialExprPrime(this);
    }

    public PSpecialOp getSpecialOp()
    {
        return this._specialOp_;
    }

    public void setSpecialOp(PSpecialOp node)
    {
        if(this._specialOp_ != null)
        {
            this._specialOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._specialOp_ = node;
    }

    public PSpecialExprPrime getSpecialExprPrime()
    {
        return this._specialExprPrime_;
    }

    public void setSpecialExprPrime(PSpecialExprPrime node)
    {
        if(this._specialExprPrime_ != null)
        {
            this._specialExprPrime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._specialExprPrime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._specialOp_)
            + toString(this._specialExprPrime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._specialOp_ == child)
        {
            this._specialOp_ = null;
            return;
        }

        if(this._specialExprPrime_ == child)
        {
            this._specialExprPrime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._specialOp_ == oldChild)
        {
            setSpecialOp((PSpecialOp) newChild);
            return;
        }

        if(this._specialExprPrime_ == oldChild)
        {
            setSpecialExprPrime((PSpecialExprPrime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
