/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ASumSpecialSyntax extends PSpecialSyntax
{
    private TSopSum _sopSum_;
    private TId _id_;

    public ASumSpecialSyntax()
    {
        // Constructor
    }

    public ASumSpecialSyntax(
        @SuppressWarnings("hiding") TSopSum _sopSum_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setSopSum(_sopSum_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new ASumSpecialSyntax(
            cloneNode(this._sopSum_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASumSpecialSyntax(this);
    }

    public TSopSum getSopSum()
    {
        return this._sopSum_;
    }

    public void setSopSum(TSopSum node)
    {
        if(this._sopSum_ != null)
        {
            this._sopSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sopSum_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sopSum_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sopSum_ == child)
        {
            this._sopSum_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sopSum_ == oldChild)
        {
            setSopSum((TSopSum) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
