/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwBreak extends Token
{
    public TKwBreak()
    {
        super.setText("break");
    }

    public TKwBreak(int line, int pos)
    {
        super.setText("break");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwBreak(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwBreak(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwBreak text.");
    }
}
