/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwColumn extends Token
{
    public TKwColumn()
    {
        super.setText("column");
    }

    public TKwColumn(int line, int pos)
    {
        super.setText("column");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwColumn(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwColumn(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwColumn text.");
    }
}
