/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwInsert extends Token
{
    public TKwInsert()
    {
        super.setText("insert");
    }

    public TKwInsert(int line, int pos)
    {
        super.setText("insert");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwInsert(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwInsert(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwInsert text.");
    }
}
