/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwImport extends Token
{
    public TKwImport()
    {
        super.setText("import");
    }

    public TKwImport(int line, int pos)
    {
        super.setText("import");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwImport(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwImport(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwImport text.");
    }
}
