/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwRemove extends Token
{
    public TKwRemove()
    {
        super.setText("remove");
    }

    public TKwRemove(int line, int pos)
    {
        super.setText("remove");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwRemove(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwRemove(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwRemove text.");
    }
}
