/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwSeparatedBy extends Token
{
    public TKwSeparatedBy()
    {
        super.setText("seperated_by");
    }

    public TKwSeparatedBy(int line, int pos)
    {
        super.setText("seperated_by");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwSeparatedBy(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwSeparatedBy(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwSeparatedBy text.");
    }
}
