/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TKwSortOrderAsc extends Token
{
    public TKwSortOrderAsc()
    {
        super.setText("asc");
    }

    public TKwSortOrderAsc(int line, int pos)
    {
        super.setText("asc");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwSortOrderAsc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwSortOrderAsc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwSortOrderAsc text.");
    }
}
