/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.parser;

import postfix.node.*;
import postfix.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNewline(@SuppressWarnings("unused") TNewline node)
    {
        this.index = 0;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 2;
    }

    @Override
    public void caseTLCbrack(@SuppressWarnings("unused") TLCbrack node)
    {
        this.index = 3;
    }

    @Override
    public void caseTRCbrack(@SuppressWarnings("unused") TRCbrack node)
    {
        this.index = 4;
    }

    @Override
    public void caseTLBrack(@SuppressWarnings("unused") TLBrack node)
    {
        this.index = 5;
    }

    @Override
    public void caseTRBrack(@SuppressWarnings("unused") TRBrack node)
    {
        this.index = 6;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 7;
    }

    @Override
    public void caseTIntnum(@SuppressWarnings("unused") TIntnum node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFloatnum(@SuppressWarnings("unused") TFloatnum node)
    {
        this.index = 9;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 10;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 11;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 12;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 13;
    }

    @Override
    public void caseTBinInfixOp(@SuppressWarnings("unused") TBinInfixOp node)
    {
        this.index = 14;
    }

    @Override
    public void caseTUnaryPrefixOp(@SuppressWarnings("unused") TUnaryPrefixOp node)
    {
        this.index = 15;
    }

    @Override
    public void caseTOpAssign(@SuppressWarnings("unused") TOpAssign node)
    {
        this.index = 16;
    }

    @Override
    public void caseTSopDot(@SuppressWarnings("unused") TSopDot node)
    {
        this.index = 17;
    }

    @Override
    public void caseTKwAs(@SuppressWarnings("unused") TKwAs node)
    {
        this.index = 18;
    }

    @Override
    public void caseTKwImport(@SuppressWarnings("unused") TKwImport node)
    {
        this.index = 19;
    }

    @Override
    public void caseTKwSeparatedBy(@SuppressWarnings("unused") TKwSeparatedBy node)
    {
        this.index = 20;
    }

    @Override
    public void caseTKwFor(@SuppressWarnings("unused") TKwFor node)
    {
        this.index = 21;
    }

    @Override
    public void caseTKwWhile(@SuppressWarnings("unused") TKwWhile node)
    {
        this.index = 22;
    }

    @Override
    public void caseTKwIn(@SuppressWarnings("unused") TKwIn node)
    {
        this.index = 23;
    }

    @Override
    public void caseTKwIf(@SuppressWarnings("unused") TKwIf node)
    {
        this.index = 24;
    }

    @Override
    public void caseTKwElse(@SuppressWarnings("unused") TKwElse node)
    {
        this.index = 25;
    }

    @Override
    public void caseTKwSortOrder(@SuppressWarnings("unused") TKwSortOrder node)
    {
        this.index = 26;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 27;
    }
}
